### ISSUE TITLE
testCases "Bson.readDate  works" and "Reading Bson values as DateTime works" both fail

### ISSUE THREAD

**Issue by akucheck** [Zaid-Ajaj/LiteDB.FSharp#21]
On a fresh install, while running ./build.sh these 2 testCases fail on the Day conversion with an offByOne error.

I'm assuming this is due to a change to LiteDB but have not been able to confirm that yet.

![litedb fsharp build errors](https://user-images.githubusercontent.com/61386/51796560-12cc1680-21ab-11e9-9dde-f454bebd9fa9.jpg)

**Comment by humhei** [comment]
I can not repro it after i update LiteDB locally (All tests are passed)
What's the exception does it throw?

**Comment by humhei** [comment]
You can set breakpoint these places to see what the error is
https://github.com/Zaid-Ajaj/LiteDB.FSharp/blob/master/LiteDB.FSharp/Json.fs#L181
https://github.com/Zaid-Ajaj/LiteDB.FSharp/blob/master/LiteDB.FSharp/Json.fs#L249

**Comment by akucheck** [comment]
setting breakpoint at #181:
![debugging litedb fsharp-1](https://user-images.githubusercontent.com/61386/51803987-0af28d80-2210-11e9-9c02-6df884680e44.jpg)

**Comment by akucheck** [comment]
did not mean to close (sorry). 
after setting breakpoint at #181:
![debugging litedb fsharp-1](https://user-images.githubusercontent.com/61386/51804012-53aa4680-2210-11e9-90d1-90c027c4b9a2.jpg)

**Comment by Zaid-Ajaj** [comment]
Hello @akucheck,

> I'm assuming this is due to a change to LiteDB but have not been able to confirm that yet.

I think this might be the case, I wil investigate, thanks a lot for reporting the issue :)

**Comment by Zaid-Ajaj** [comment]
@akucheck Seems to be fixed, can you pull a fresh clone and run the tests again? :smile:

please re-open the issue if the problem persists

**Comment by akucheck** [comment]
Happy to.

ak

**Comment by akucheck** [comment]
Zaid-Ajaj:

Works like a champ.  thanks!

ak
