### ISSUE TITLE
Your platform does not support FileStream.Lock

### ISSUE THREAD

**Issue by akucheck** [Zaid-Ajaj/LiteDB.FSharp#23]
It appears that LiteDB now needs a config setting for mode=exclusive on MacOS. I cannot find a way to do this. On initial load, once compile has finished I'm getting this:
![litedb fsharp mode error](https://user-images.githubusercontent.com/61386/52922538-d174e580-32d6-11e9-9e29-4fd985c6848f.jpg)

**Comment by Zaid-Ajaj** [comment]
Hello @akucheck, looks like you are running tabula-rasa project. Setting the connection string happens in [here](https://github.com/Zaid-Ajaj/tabula-rasa/blob/master/Server/Storage.fs#L31-L33) in case you using the local database, which uses the absolute file name of the databse as the connection string. 

You can override that and use the following instead:
```fs
let createDatabaseUsing store =
    let mapper = FSharpBsonMapper()
    match store with
    | Store.InMemory -> 
        let memoryStream = new System.IO.MemoryStream()
        new LiteDatabase(memoryStream, mapper)
    | Store.LocalDatabase -> 
        let dbFile = Environment.databaseFilePath
        // extend the connection string here
        let connectionString = sprintf "Filename=%s; Mode=Exclusive" dbFile 
        new LiteDatabase(connectionString , mapper)
```
Can you check whether this fixes the problem for you?

**Comment by akucheck** [comment]
It does indeed fix the problem.  Thanks much!

On to playing with this puppy to learn more about SAFE-stack.

ak
