### ISSUE TITLE
Unhandled Exception-Method not found: ..LiteRepository.Insert... at ...FSharp.Extensions.LiteRepository.insertItem...

### ISSUE THREAD

**Issue by srlopez** [Zaid-Ajaj/LiteDB.FSharp#25]
Continuing with my first steps, I find that I still need to include some module.
I get the following error addressed from the following line: `LiteRepository.insertItem eorder`

```
Unhandled Exception: System.MissingMethodException: Method not found: 'Void LiteDB.LiteRepository.Insert(System.__Canon, System.String)'.
   at LiteDB.FSharp.Extensions.LiteRepository.insertItem[a](a item, LiteRepository lr)
   at Program.main(String[] argv) in /app/appbook/Program.fs:line 248
```

```
    let eorder = { Id = 1; Items = [item1;item2];  OrderNumRange = "" }

    let queryedEOrder =
        db 
        |> LiteRepository.insertItem eorder
        |> LiteRepository.query<EOrder> 
        |> LiteQueryable.first

    match queryedEOrder.Items with 
    | [item1;item2] -> 
        match item1,item2 with 
        | :? IBarcode,:? IColor -> 
            pass()
        | _ -> fail()   
    | _ -> fail()
  
    printfn "Hello World from F#!"
    0 // return an integer exit code
```

**Comment by Zaid-Ajaj** [comment]
Hmm looks like a nasty exception we got here, this is usually due to assemblies not properly loaded. I will need a bit more information: 
 - What version of LiteDB.FSharp are you using
 - Which `dotnet --version` or which target if you are using Full Framework? 
 - Are you using paket or nuget?

**Comment by srlopez** [comment]
On my fsproj file
```
    <PackageReference Include="LiteDB" Version="4.1.4" />
    <PackageReference Include="LiteDB.FSharp" Version="2.7.0" />
 ```
And this are the version
```
$ dotnet --version
2.2.203
$ uname -a
Linux SAFE 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 GNU/Linux
```
I just try yo reproduce your examples on README.md

By the way. ¿Is it possible to integrate F# Classes, like Records, to save to LiteDB?

**Comment by Zaid-Ajaj** [comment]
Thanks a lot @srlopez, I will investigate this further. Though these example should have worked because they are all unit-tested.

**Comment by Zaid-Ajaj** [comment]
Found it, you are using incompatible versions of `LiteDB` and `LiteDB.FSharp`:
```xml
<PackageReference Include="LiteDB" Version="4.1.4" />
<PackageReference Include="LiteDB.FSharp" Version="2.7.0" />
```
The fix is to remove `<PackageReference Include="LiteDB" Version="4.1.4" />` from your package references and run `dotnet restore && dotnet run` because the right version will be pulled in a dependency of `LiteDB.FSharp`, so your project file will look something like:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiteDB.FSharp" Version="2.7.0" />
  </ItemGroup>

</Project>
```
 Can you please confirm the fix when you remove the `LiteDB` package reference and run `dotnet restore && dotnet run`, I will close the issue for now, please re-open if the problem persists.

**Comment by srlopez** [comment]
Confirmed & Thanks!
Removing `<PackageReference Include="LiteDB" Version="4.1.4" />` from `app.fsproj` and `dotnet restore && dotnet run` print passed! on the screen:
```
dotnet restore && dotnet run
  Restore completed in 3.95 sec for /app/appbook.fsproj.
passed
Hello World from F#!
```
Thanks
