### ISSUE TITLE
The client code that uses the library must know a lot about it.

### ISSUE THREAD

**Issue by srlopez** [Zaid-Ajaj/LiteDB.FSharp#28]
Hi again,
Sorry for the list of issues I'm publishing, but I do it for the benefit of the code and to be clearer readability.

I think that the code that uses the library must know a lot about it.

First: **The code must know about the name of the values**.
When I want to delete a record by its identifier, expressing it clearly.
The code **`computers.Delete(Query.LT("Id", BsonValue(myPc.Id-3)))`**
 does not work. In the register, **Id** is a value, but as a programmer I have to know that it is stored as **_id,** in order to use it, and so **`computers.Delete(Query.LT("_id", BsonValue(myPc.Id-3)))`** works correctly.
I don't know if it's so by design, or it's a simple mistake that can be easily fixed.

Second: **The code must know the underlying Bson format**.
For each Query/Find I must indicate previously a **conversion to Bson,** as in the previous example, or the simple `computers.FindById(BsonValue(1))` or `computers.Find(Query.EQ("Manufacturer", BsonValue("System77"))) |> Seq.iter (printfn "%A")`. It's harder to read. 
In the C# version it seems to me that the conversion is done internally.
```
var results = col.Find(Query.StartsWith("Name", "Jo"));
var results = col.Find(Query.GT("Products[*].Price", 100))
```
I think doing it inside the wrapper would help to clarify the code and it would be more F# idiomatic. It's a simple modification, but it's structural. Maybe for the next version 3.

Tell me what you think.
And thank you again

**Comment by Zaid-Ajaj** [comment]
Hello @srlopez, you seem to have found the problem that this library solves for F# ;) The description says: "... with type-safe query expression through F# quotations" which is how you should query your data without needing to know about `BsonDocuments`. 

In the README there are many examples of querying the data using quotations but you have to open the namespace `LiteDB.FSharp.Extensions` and your `LiteCollection` will have extensions methods:
```fs
let collection = db.GetCollection<MyType>("collection")
collection.findOne (fun item -> ... )
collection.findMany (fun item -> ... )
collection.tryFindOne (fun item -> ... )
collection.delete (fun item -> ....)
collection.fullseach <@ fun item -> item.Prop @> (fun prop -> ...)
collection.where <@ fun item -> item.Prop @> (fun prop -> ...)
```
Example
```fs
open LiteDB
open LiteDB.FSharp
open LiteDB.FSharp.Extensions

type Person = { Id: int; Name: string; Age: int; Email: string } 
let people = db.GetCollection<Person>("people ")

// find by Id
let exactPerson = people.findOne (fun p -> p.Id = 1)

let john = people.findOne (fun person -> person.Name.StartsWith "John")

let adults = people.findMany (fun person -> person.Age >= 18) 

let nonEmptyEmails = people.findMany (fun person -> not (string.IsNullOrEmpty person.Email) )

// composite queries
let adultDoe = people.findMany (fun person -> person.Age >= 18 && person.Name.Contains "Doe")
``` 
I thought I properly documented these function but I guess I can never have enough documentation :smile:

**Comment by srlopez** [comment]
Thanks again .
Learning a los width you.

**Comment by Zaid-Ajaj** [comment]
Is the problem resolved? I will close this issue for now, please re-open or open an other issue if encounter other problems

**Comment by srlopez** [comment]
Hello again @Zaid-Ajaj .
First of all sorry, I haven't read the documentation with the attention it deserves. Serious error, very serious, on my part.


Your solution (the one I will use for my projects), very correct, functional, simple and very academically precise, leads me to raise a deeper doubt (I really like to talk about deep concepts, imagine we are with a few beers), and in this case the concept is "Simplicity".


I am here, learning F# (and teaching it) because I want my students to learn to model a domain with the expressiveness and simplicity that F# gives us, saving paradigms and excuses from the OOP, very well expressed by _Scott Wlaschin_ in his famous book **"Domain Modeling Made Functional"**, and _Isaac Abraham in_ **"Get Programming with F#"**. You can not help but falling in love with the simplicity with which these authors present their model solution to real problems in the company. The other alternative was to use Object Constraint Language (OCL) from OMG (OhMG!). Who wants to use that having F#? 

DDD focuses on communication between developers and domain experts, isolating them from the underlying technology (Functional or OO). Scott shares F# models with clients, and they understand them!
If we want to make F# a success as a business language and not just for making web pages (Right for SAFE!), or an academic experiment for ML, we must involve the clients, the experts in the domain.

If I want to model a domain in which to look for a computer by Id, and make it simple for the client to read it and understand it. I will have to encapsulate the lambdas into registry members (just an idea):
```
Type Computer...

member this.FindOne("value", value) = ... computers.findOne (fun c -> c. "value" = value)
``` 
What introduces a little complexity, and leads me to the OOP is the solution to hide the complexity of lambdas expressions (for experts in the domain).

Nice paradox.

**Comment by srlopez** [comment]
There's still something that doesn't work for me when I id.
    `computers.delete(fun c -> c.Id < 4)` or 
`    computers.findMany (fun c -> c.Id>3) |> Seq.iter (printfn "%A")` 
do not execute anything, do not send error messages.
But if I use any other property it works.
`    computers.findMany (fun c -> c.CPU = Intel) |> Seq.iter (printfn "%A")
` or `computers.delete(fun c -> c.Manufacturer.Contains "m")` 
does the work.

Event worse width id in a expression: `    computers.delete(fun c -> c.Id < myPc.Id-4)`

```
Unhandled Exception: System.Exception: Failed to construct a query from the expression: 
Call (None, op_LessThan,
      [PropertyGet (Some (c), Id, []),
       Call (None, op_Subtraction,
             [PropertyGet (Some (ValueWithName (Computer #103: Dell/1:[...GB],
                                                myPc)), Id, []), Value (4)])])

   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1647.Invoke(String message)
   at LiteDB.FSharp.Extensions.LiteCollection`1.delete[T,t](LiteCollection`1 collection, FSharpExpr`1 expr)
   at Program.main(String[] argv) in /app/Program.fs:line 83
```
