### ISSUE TITLE
Mono linker could not resolve a proper method

### ISSUE THREAD

**Issue by vshapenko** [Zaid-Ajaj/LiteDB.FSharp#32]
Hello! I am trying to use your library for my fabulous project, and i am getting following  error:
Mono.Linker.MarkException: Error processing method: 'LiteDB.LiteRepository LiteDB.FSharp.Extensions/LiteRepository::insertItem(a,LiteDB.LiteRepository)' in assembly: 'LiteDB.FSharp.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void LiteDB.LiteRepository::Insert(!!0,System.String)
   в Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   в Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   в Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   в Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   в Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   в Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- Конец трассировки внутреннего стека исключений ---
   в Mono.Linker.Steps.MarkStep.ProcessQueue()
   в Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   в Mono.Linker.Steps.MarkStep.Process()
   в MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   в Mono.Linker.Pipeline.Process(LinkContext context)
   в MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   в Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   в Xamarin.Android.Tasks.LinkAssemblies.Execute()
   в Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   в Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

Looks like mono linker needs more type annotation to determine which method to use

**Comment by humhei** [comment]
```fsharp
LiteRepository::insertItem(a,LiteDB.LiteRepository)
```
Hello. 
What is the type of a? 
[LiteRepository.insertItem](https://github.com/Zaid-Ajaj/LiteDB.FSharp/blob/master/LiteDB.FSharp/Extensions.fs#L98) is a single wrapper to LiteRepository.Insert
```fsharp
        let insertItem<'a> (item: 'a) (lr:LiteRepository) =
            lr.Insert<'a>(item)
            lr
```

**Comment by vshapenko** [comment]
Hello, this issue should be closed. My bad
