### ISSUE TITLE
build.sh doesn't work anymore - replacement needed?

### ISSUE THREAD

**Issue by TeaDrivenDev** [Zaid-Ajaj/LiteDB.FSharp#50]
When doing #47, I completely overlooked the `build.sh` script, which a) is now largely obsolete, because Mono isn't needed anymore, and b) doesn't work anymore, because there's no `fake.exe`. However, the build script now requires the .NET Core FAKE runner, which the repository doesn't provide a way of obtaining.

There are two (or three) ways of dealing with this:
- Just delete `build.sh` and expect anyone wanting to build the repository to have `fake-cli` installed as a .NET Core "global tool". I suppose that will be the case for most open source-affine F# developers.
- Bootstrap FAKE as a "local tool" along the lines of [https://github.com/FakeBuild/fake-bootstrap/tree/local_tool](https://github.com/FakeBuild/fake-bootstrap/tree/local_tool). This would be the most user friendly option, but may be overkill for a project with such a limited and specific scope.
- Bootstrap FAKE as a "global tool" as in [https://github.com/FakeBuild/fake-bootstrap/tree/global_tool](https://github.com/FakeBuild/fake-bootstrap/tree/global_tool). While it is an option, I don't think an individual project should do that. I consider global tools something the user should explicitly take care of themselves.

**Comment by Zaid-Ajaj** [comment]
Replaced FAKE with a simple console app that uses some of FAKE modules. Now to build or test the application:
```bash
cd ./LiteDB.FSharp.Build
dotnet run -- build
dotnet run -- test
dotnet run -- pack
dotnet run -- publish
```
etc.
