### ISSUE TITLE
Serializing and deserializing f# functions is not supported

### ISSUE THREAD

**Issue by humhei** [Zaid-Ajaj/LiteDB.FSharp#7]
Today i tried to do make a model something like this 
```fsharp
[<CLIMutable>]
type Product =
    {
        Id: int
        Name: string
        //PrinterKey: Expression<Func<Item,obj>>
        ImposerKey: obj -> obj
    }
```
When i deserialized it from database, below exception was thrown
```
Newtonsoft.Json.JsonSerializationException: 'Could not create an instance of type Microsoft.FSharp.Core.FSharpFunc`2[System.Object,System.Object]. Type is an interface or abstract class and cannot be instantiated. Path 'Products[0].ImposerKey', line 1, position 133.'
```

**Comment by Zaid-Ajaj** [comment]
Serializing arbitrary functions into Bson (or any persistence mechanism) doesn’t really make sense, what do you expect the library to do?

**Comment by humhei** [comment]
Currently i use it as `property expression`   to support dynamic ORM in `fsx` 
I need to transform  fsharp type bson datas to `csv` so it can be invoked by other UI program
```fsharp
Seq.csvWithProp  (Expr.prop (fun (it:Item) -> 
    it.Brand,it.Art,it.Size,it.Barcode,it.Image,it.Material)) items
```

**items** is retrived from litedb  so i think 
```
Expr.prop (fun (it:Item) -> 
it.Brand,it.Art,it.Size,it.Barcode,it.Image,it.Material
```
should also be retrived from litedb
![image](https://user-images.githubusercontent.com/25994449/39116677-9f0bd3de-4717-11e8-9a01-4e6e8188eb2c.png)

**Comment by humhei** [comment]
I tried https://github.com/Microsoft/fsharplu it taked the some exception
while https://github.com/mbraceproject/FsPickler can serialize and deserialize function but is not compact to https://github.com/mbdavid/LiteDB

**Comment by humhei** [comment]
For me there are two solutions
- Making a compact library between dotnet json and FsPickler
- Makeing `it.Brand,it.Art,it.Size,it.Barcode,it.Image,it.Material` as a text and then create a property expression from this text

**Comment by humhei** [comment]
I think i will take some time to see if the first solution is  feasible or not

**Comment by Zaid-Ajaj** [comment]
Another simpler solution is to persist the fields as a list of strings such as [“Brand”; “Art”] and then: 

dynamicallyRead item [“Brand”; “Size”] => [“Play ...”; “35” ] 

Where dynamicallyRead uses reflection on the fields of items to retrieve their values

**Comment by Zaid-Ajaj** [comment]
Nested property values can have a path i.e. [“NestedField.PropName”]

A general solution to persisting arbitrary logic in functions is not a good fit for this particular problem, there is always a simpler solution

**Comment by humhei** [comment]
Thanks for answer 😀

**Comment by humhei** [comment]
I still encounter this problem 😓 
follow is my AST
```fsharp
[<CLIMutable>]
type Item = 
    {
        Id: int
        Template: string option
        Art: string
        Brand: string option
        Color: ColorEnum option
        Material: Material option
        Image: string option
        Barcode: string option
        Sex: Sex option
        Fraction: int option
        Code: int option
        SizeRange: string option
        EUR: float
        US: float option
        UK: float option
        CM: float option
        Price: string option
        Number: int 
    }
[<CLIMutable>]
type Order =
    {
        Id: int
        Name: string
        Items: Item list
        Date: DateTime
    }
[<CLIMutable>]
type Product =
    {
        Id: int
        Name: string
        Kind: ProductKind
        Orders: Order list
        UnitPrice: float
        Paper: Paper option
    }
```

Now i want to add a `Filter` to `Product` to conditionally determine whether this product take effect 
The logic of product taking effect is arbitrary ,Because customs 's logic is always not the some :)
For example
- the customer said the item with ART contains "CROSS DOCK" doesn't has this product
- the brand named with "PLAY   URBAN" should use different product but with "LIP LOVER" must use this product 
```fsharp
[<CLIMutable>]
type Product =
    {
        Filter: Item -> bool
        Id: int
        Name: string
        Kind: ProductKind
        Orders: Order list
        UnitPrice: float
        Paper: Paper option
    }
```

**Comment by Zaid-Ajaj** [comment]
Your business logic should be in your code, not in your storage system. The only reason you would store arbitrary filters *inside* the database, is to be able to update them by hand (without the application) which I don't think you actually want. 

You would put this kind of logic in place where you are reading the values from the database in a `where` query:
```fs
// order that contains any item with "CROSS DOCK" is invalid 
let orderHasInvalidItems (order : Order) = 
  Seq.forall (fun item -> item.Art.Contains("CROSS DOCK")) order.Items) 

// get all products of which the orders are valid (their items do not contain "CROSS DOCK") 
let getActiveProducts (db: ILiteDatabase) = 
  let products = db.GetCollection<Product> "products"
  products.where 
      <@ fun prod -> prod.Orders @> 
      (fun orders -> Seq.forall (fun order -> not (orderHasInvalidItems  order) orders) 
```
otherwise if you really needed to store F# filters, I suggest you use a simple embedded DSL that you can serialize to the database (then you will be doing what LiteDB is doing for you now):
```fs
type FilterExpr = 
  | NoFilter 
  | Equals of propName:string * value:obj 
  | LessThan of propName:string * value:float 
  | GreaterThan of propName:string * value:float 
  | Contains of propName:string * value:string 
  | And of left:FilterExpr * right:FilterExpr 
  | Or of left:FilterExpr * right:FilterExpr  
  | Not of expr:FilterExpr 
  | NestedFilter of propName:string * filter:FilterExpr 
```
You will also need to evaulate the expr yourself against dynamic record values from the database

**Comment by Zaid-Ajaj** [comment]
I am assuming you solved your issue, if it happened to be the case that you still need to serialize or deserialize functions, then just use a `byte[]` as the data format to store the function with FsPickler for converting between the bytes and functions. This way you don't need to integrate FsPickler with this library internally

**Comment by humhei** [comment]
> then just use a byte[] as the data format to store the function with FsPickler 

I like this way 👍 ,It's flexible.
I may finally directly write function in `.fsx` file (do everything in it,assum it a middleware to database and my ui program)

**Comment by humhei** [comment]
Thanks for your answer again! 😄

**Comment by Zaid-Ajaj** [comment]
@humhei No problem, happy to help ;)

**Comment by humhei** [comment]
Also find a  alternative way want to share you
@Zaid-Ajaj 
Using excel UDF by Excel DNA https://github.com/Excel-DNA to store functions
Moreever, With [Dynamic array formulas](https://support.office.com/en-us/article/dynamic-array-formulas-in-non-dynamic-aware-excel-696e164e-306b-4282-ae9d-aa88f5502fa2) is really cool
